@startuml phy_handler_basic_callback

!theme cerulean
skinparam DefaultFontSize 16
skinparam defaultFontName Gotham Black

skinparam defaultTextAlignment center

start
:Save the modem time;
if (error ?) then (yes)
    -[dashed]->
    :Log the error;
    -[dashed]->
else (no)
    :Do something
    related to
    the operation;

    :Notify the queue that
    the PHY is ready;
endif
stop

@enduml